name: Node.js CI

on:
  pull_request: ~
# env:
#   REACT_APP_STATSIG_SDK_KEY: 123
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run tests
        run: npm run test
